### ISSUE TITLE
Add Customised CSS to notifications

### ISSUE THREAD

**Issue by ankitaYadav02** [tjrexer/react-notifications#60]
Unable to change the width of notification and content in the notification is overflowing.

**Comment by adam-carruthers** [comment]
You can add CSS yourself to change the width.

Just create a css file, import it in another react file then put in that file

```css
.notification-container {
  width: 500px!important;
}
```
